package edn.cloud.sfactor.persistence.dao;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.NoResultException;
import javax.persistence.NonUniqueResultException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import edn.cloud.sfactor.business.persistence.manager.EntityManagerProvider;
import edn.cloud.sfactor.persistence.entities.DBQueries;
import edn.cloud.sfactor.persistence.entities.Generated;

public class GeneratedDAO extends BasicDAO<Generated> 
{
	private final Logger logger = LoggerFactory.getLogger(this.getClass());

	public GeneratedDAO() {
		super(EntityManagerProvider.getInstance());
	}
	
	public List<Generated> getByDocId(Long docId) {
		final EntityManager em = emProvider.get();
		try {
			final TypedQuery<Generated> query = em.createNamedQuery(DBQueries.GET_GENERATED_BY_ID, Generated.class);
			query.setParameter("docId", docId); //$NON-NLS-1$
			List<Generated> gen = query.getResultList();
			logger.info(gen.toString());
			return gen;
		} catch (NoResultException x) {
			logger.warn("Could not retrieve entity for userId {} from table {}. Maybe the user doesn't exist yet.", docId, "User"); //$NON-NLS-1$ //$NON-NLS-2$
		} catch (NonUniqueResultException ex) {
			throw new IllegalStateException(String.format("More than one entity for userId %s from table User.", docId), ex); //$NON-NLS-1$
		}

		return null;
	}
	
	/**
	 * delete all generated by document
	 * @param Long idDoc
	 * @return boolean
	 * */
	public boolean deleteAllByDocId(Long idDoc) 
	{
		final EntityManager em = emProvider.get();
		
		try 
		{
			EntityTransaction tx = em.getTransaction();
			tx.begin();
			
			final Query query = em.createQuery("delete from Generated u where u.document.id =:id ");
			query.setParameter("id", idDoc);
			
			query.executeUpdate();
			tx.commit();
			return true;
		}
		catch (Exception e) 
		{
			throw new IllegalStateException("Error deleteAllByDocId", e); //$NON-NLS-1$	
		}	
	}	
}
