package edn.cloud.sfactor.business.impl;

import java.util.List;
import edn.cloud.sfactor.business.interfaces.SucessFactorGenerator;
import edn.cloud.sfactor.persistence.dao.GeneratedDAO;
import edn.cloud.sfactor.persistence.dao.DocumentSignatureDAO;
import edn.cloud.sfactor.persistence.entities.Generated;
import edn.cloud.sfactor.persistence.entities.DocumentSignature;

public class SuccessFactorGenerateImpl implements SucessFactorGenerator
{
	 /** save generated document
	 * @param Generated generateDoc
	 * */
	public Generated saveGeneratedDocument(Generated generateDoc)
	{
		GeneratedDAO dao = new GeneratedDAO();
		return dao.saveNew(generateDoc);		
	}
	
	/**
	 * get document generated
	 * @param Long docId
	 * */
	public List<Generated> getGeneratedByIdDoc(Long docId)
	{
		GeneratedDAO dao = new GeneratedDAO();
		List<Generated> objectArray = dao.getByDocId(docId);
		return objectArray;
	}
	
	/**
	 * get generated by id
	 * @param Long idGenerated
	 * */
	public Generated getGeneratedById(Long idGenerated)
	{
		GeneratedDAO dao = new GeneratedDAO();
		Generated objectArray = dao.getById(idGenerated);
		return objectArray;
	}
	
	/**
	 * Save signature asociate to document
	 * @param DocumentSignature entity
	 * @return id Signature Document
	 * */
	public Long saveDocumentSignature(DocumentSignature entity)
	{
		DocumentSignatureDAO dao = new DocumentSignatureDAO();
		dao.saveNew(entity);
		return entity.getId();
	}
}
